// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestStreamRender;

#nullable disable

namespace TestStreamRender.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240316165852_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("TestStreamRender.Models.TestModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4441c0c4-59a3-42a2-b670-65d551159dbb"),
                            Test = "TEST1"
                        },
                        new
                        {
                            Id = new Guid("78d1afe8-dd40-4ae1-83df-5cd6a7421d9b"),
                            Test = "TEST2"
                        },
                        new
                        {
                            Id = new Guid("f3aed082-7665-433f-8b20-c00b9ca409d2"),
                            Test = "TEST3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
